[project]
name = "barkueue"
version = "0.0.1"
description = "A lightweight task queue, easy to embed. / 一个轻量级任务队列，易于嵌入到现有业务系统。"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.1",
    "pyodbc>=5.3.0",
]

[dependency-groups]
dev = [
    "mypy>=1.19.0",
]
